# Generated by Django 4.2.26 on 2026-06-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecard',
            name='pc_image',
            field=models.ImageField(blank=True, null=True, upload_to='pricecards/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='pricecard',
            name='pc_title',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
