# Generated by Django 4.2.26 on 2026-06-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_pricecard_pc_image_pricecard_pc_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pricecards/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='price.pricecard', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Изображение карточки',
                'verbose_name_plural': 'Изображения карточек',
                'ordering': ['order'],
            },
        ),
    ]
