name: ilia-website
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: my_website_db
    ports:
      - "5432:5432"
    volumes:
      - website-db:/var/lib/postgresql
volumes:
  website-db:
