name: ilia-website
services:
  django:
    build:
      context: .
    image: website-app
    restart: unless-stopped
    container_name: website-app
    env_file:
      - .env
    environment:
      - DJANGO_DB_HOST=db
    expose:
      - 8000
    volumes:
      - website-static:/app/static_collected
      - website-media:/app/media
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: webserver
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - website-static:/usr/share/nginx/html/website-static:ro
      - website-media:/usr/share/nginx/html/website-media:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"

  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: website-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: my_website_db
    volumes:
      - website-db:/var/lib/postgresql/data

volumes:
  website-db:
  website-static:
  website-media:
