# Generated by Django 4.2.26 on 2026-09-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_alter_telesettings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=50, verbose_name='API ID')),
                ('api_hash', models.CharField(max_length=100, verbose_name='API Hash')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('two_step_password', models.CharField(blank=True, max_length=200, null=True, verbose_name='Пароль 2FA')),
                ('session_string', models.TextField(blank=True, null=True, verbose_name='Сессия (заполняется автоматически)')),
            ],
            options={
                'verbose_name': 'Настройку юзербота',
                'verbose_name_plural': 'Настройки юзербота',
            },
        ),
        migrations.AlterField(
            model_name='telesettings',
            name='tg_chat',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Чат айди'),
        ),
        migrations.AlterField(
            model_name='telesettings',
            name='tg_message',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='telesettings',
            name='tg_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Токен'),
        ),
    ]
