# Generated by Django 5.2.7 on 2025-10-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprogress',
            old_name='autoclicker_level',
            new_name='autoclicker_power',
        ),
        migrations.RenameField(
            model_name='playerprogress',
            old_name='money_per_click',
            new_name='click_power',
        ),
        migrations.RenameField(
            model_name='playerprogress',
            old_name='money',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='playerprogress',
            name='email',
        ),
    ]
