# Generated by Django 5.2.7 on 2025-10-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_autoclicker_level_playerprogress_autoclicker_power_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprogress',
            old_name='score',
            new_name='money',
        ),
    ]
