# Generated by Django 5.2.7 on 2025-10-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_score_playerprogress_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprogress',
            old_name='click_power',
            new_name='money_per_click',
        ),
    ]
