# Generated by Django 5.2.7 on 2025-10-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_click_power_playerprogress_money_per_click'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprogress',
            old_name='autoclicker_power',
            new_name='autoclicker_level',
        ),
    ]
