# Generated by Django 5.2.7 on 2025-10-26 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_autoclicker_power_playerprogress_autoclicker_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerprogress',
            options={'verbose_name': 'Прогресс игрока', 'verbose_name_plural': 'Прогресс игроков'},
        ),
        migrations.AddField(
            model_name='playerprogress',
            name='last_save',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playerprogress',
            name='money',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprogress',
            name='money_per_click',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='playerprogress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
