# Generated by Django 5.2.7 on 2025-11-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_playerprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprogress',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprogress',
            name='money_per_click',
            field=models.IntegerField(default=1),
        ),
    ]
