# Generated by Django 4.2.26 on 2026-06-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20201119_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuscrm',
            name='Status_name',
        ),
        migrations.AlterField(
            model_name='comentcrm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statuscrm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='statuscrm',
            name='status_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название статуса'),
        ),
    ]
